var searchData=
[
  ['each_20of_20them_20this_20seems_20pretty_20tedious_0',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_extern_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['effects_1',['Effects',['../md_extern_2googletest_2docs_2gmock__cook__book.html#MockingSideEffects',1,'Mocking Side Effects'],['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md247',1,'Side Effects']]],
  ['effects_2',['Matchers must have no side-effects',['../md_extern_2googletest_2docs_2gmock__cook__book.html#PureMatchers',1,'']]],
  ['elapsed_20time_3',['Suppressing the Elapsed Time',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md72',1,'']]],
  ['elapsed_5ftime_20testresult_3a_3aelapsed_5ftime_4',['elapsed_time {#TestResult::elapsed_time}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md373',1,'']]],
  ['elapsed_5ftime_20testsuite_3a_3aelapsed_5ftime_5',['elapsed_time {#TestSuite::elapsed_time}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md301',1,'']]],
  ['elapsed_5ftime_20unittest_3a_3aelapsed_5ftime_6',['elapsed_time {#UnitTest::elapsed_time}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md333',1,'']]],
  ['elemfromlist_7',['ElemFromList',['../structtesting_1_1internal_1_1ElemFromList.html',1,'testing::internal']]],
  ['elemfromlist_3c_20i_2c_20t_2e_2e_2e_20_3e_8',['ElemFromList&lt; I, T... &gt;',['../structtesting_1_1internal_1_1ElemFromList.html',1,'testing::internal']]],
  ['elemfromlistimpl_9',['ElemFromListImpl',['../structtesting_1_1internal_1_1ElemFromListImpl.html',1,'testing::internal']]],
  ['elemfromlistimpl_3c_20std_3a_3aindex_5fsequence_3c_20i_2e_2e_2e_20_3e_20_3e_10',['ElemFromListImpl&lt; std::index_sequence&lt; I... &gt; &gt;',['../structtesting_1_1internal_1_1ElemFromListImpl_3_01std_1_1index__sequence_3_01I_8_8_8_01_4_01_4.html',1,'testing::internal']]],
  ['emacs_11',['Running Tests in Emacs',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md165',1,'']]],
  ['emptybasenameparaminst_12',['EmptyBasenameParamInst',['../classEmptyBasenameParamInst.html',1,'']]],
  ['emptytesteventlistener_13',['EmptyTestEventListener',['../classtesting_1_1EmptyTestEventListener.html',1,'testing::EmptyTestEventListener'],['../md_extern_2googletest_2docs_2reference_2testing.html#EmptyTestEventListener',1,'EmptyTestEventListener']]],
  ['enabling_20disabled_20tests_14',['Temporarily Enabling Disabled Tests',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md65',1,'']]],
  ['encountered_20default_20action_20taken_20should_20i_20panic_15',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md199',1,'']]],
  ['entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20tt_20deathtest_20tt_20when_20it_20uses_20tt_20assert_5fdeath_20tt_16',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['entire_20test_20suite_20tt_20deathtest_20tt_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_17',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['environment_18',['Environment',['../classtesting_1_1Environment.html',1,'testing::Environment'],['../md_extern_2googletest_2docs_2reference_2testing.html#Environment',1,'Environment']]],
  ['environment_3a_3asetup_19',['SetUp {#Environment::SetUp}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md277',1,'']]],
  ['environment_3a_3ateardown_20',['TearDown {#Environment::TearDown}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md278',1,'']]],
  ['environmentinvocationcatcher_21',['EnvironmentInvocationCatcher',['../classtesting_1_1internal_1_1EnvironmentInvocationCatcher.html',1,'testing::internal']]],
  ['eqhelper_22',['EqHelper',['../classtesting_1_1internal_1_1EqHelper.html',1,'testing::internal']]],
  ['error_20messages_23',['Predicate Assertions for Better Error Messages',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md15',1,'']]],
  ['error_20tt_20no_20matching_20function_20for_20call_20to_20footest_3a_3afootest_20tt_20why_24',['I have a fixture class &lt;tt&gt;FooTest&lt;/tt&gt;, but &lt;tt&gt;TEST_F(FooTest, Bar)&lt;/tt&gt; gives me error &lt;tt&gt;&quot;no matching function for call to `FooTest::FooTest()&apos;&quot;&lt;/tt&gt;. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md100',1,'']]],
  ['errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_25',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md87',1,'']]],
  ['even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_26',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['event_20listeners_27',['Event Listeners',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md56',1,'Defining Event Listeners'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md57',1,'Using Event Listeners']]],
  ['eventrecordinglistener_28',['EventRecordingListener',['../classtesting_1_1internal_1_1EventRecordingListener.html',1,'testing::internal']]],
  ['eventrecordinglistener2_29',['EventRecordingListener2',['../classtesting_1_1internal_1_1EventRecordingListener2.html',1,'testing::internal']]],
  ['events_30',['Extending GoogleTest by Handling Test Events',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md55',1,'']]],
  ['exactly_31',['Matching Argument Values Exactly',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md129',1,'']]],
  ['example_32',['Basic Example',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md167',1,'']]],
  ['exception_33',['Asserting on Subroutines with an exception',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['exception_20assertions_34',['Exception Assertions',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md14',1,'Exception Assertions'],['../md_extern_2googletest_2docs_2reference_2assertions.html#exceptions',1,'Exception Assertions']]],
  ['exceptions_35',['Disabling Catching Test-Thrown Exceptions',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md79',1,'']]],
  ['excessivearg_36',['ExcessiveArg',['../structtesting_1_1internal_1_1ExcessiveArg.html',1,'testing::internal']]],
  ['execution_37',['Skipping test execution',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md26',1,'']]],
  ['execution_20upon_20first_20failure_38',['Stop test execution upon first failure',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['existing_20boolean_20function_39',['Using an Existing Boolean Function',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md16',1,'']]],
  ['existing_20cmake_20project_40',['Incorporating Into An Existing CMake Project',['../md_extern_2googletest_2googletest_2README.html#autotoc_md399',1,'']]],
  ['existing_20code_41',['Simplifying the Interface without Breaking Existing Code',['../md_extern_2googletest_2docs_2gmock__cook__book.html#SimplerInterfaces',1,'']]],
  ['exit_42',['EXIT',['../app_8hpp.html#a5be5e47a3042bc91460d05e47f32120da7a10b5d68d31711288e1fe0fa17dbf4f',1,'app.hpp']]],
  ['exit_43',['Detecting Test Premature Exit',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md77',1,'']]],
  ['expect_44',['Expect',['../md_extern_2googletest_2docs_2gmock__cook__book.html#UseOnCall',1,'Knowing When to Expect'],['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md215',1,'Matchers: What Arguments Do We Expect?']]],
  ['expect_5f_20statements_20in_20matchers_45',['Using EXPECT_ Statements in Matchers',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md169',1,'']]],
  ['expect_5fany_5fthrow_46',['EXPECT_ANY_THROW',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_ANY_THROW',1,'']]],
  ['expect_5fcall_47',['EXPECT_CALL',['../md_extern_2googletest_2docs_2reference_2mocking.html#EXPECT_CALL',1,'']]],
  ['expect_5fcall_20after_48',['After {#EXPECT_CALL.After}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md268',1,'']]],
  ['expect_5fcall_20insequence_49',['InSequence {#EXPECT_CALL.InSequence}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md267',1,'']]],
  ['expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_50',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['expect_5fcall_20retiresonsaturation_51',['RetiresOnSaturation {#EXPECT_CALL.RetiresOnSaturation}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md271',1,'']]],
  ['expect_5fcall_20times_52',['Times {#EXPECT_CALL.Times}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md266',1,'']]],
  ['expect_5fcall_20willonce_53',['WillOnce {#EXPECT_CALL.WillOnce}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md269',1,'']]],
  ['expect_5fcall_20willrepeatedly_54',['WillRepeatedly {#EXPECT_CALL.WillRepeatedly}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md270',1,'']]],
  ['expect_5fcall_20with_55',['With {#EXPECT_CALL.With}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md265',1,'']]],
  ['expect_5fdeath_56',['EXPECT_DEATH',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_DEATH',1,'']]],
  ['expect_5fdeath_5fif_5fsupported_57',['EXPECT_DEATH_IF_SUPPORTED',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_DEATH_IF_SUPPORTED',1,'']]],
  ['expect_5fdebug_5fdeath_58',['EXPECT_DEBUG_DEATH',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_DEBUG_DEATH',1,'']]],
  ['expect_5fdouble_5feq_59',['EXPECT_DOUBLE_EQ',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_DOUBLE_EQ',1,'']]],
  ['expect_5feq_60',['EXPECT_EQ',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_EQ',1,'']]],
  ['expect_5feq_20htonl_20blah_20blah_5fblah_20generates_20weird_20compiler_20errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_61',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md87',1,'']]],
  ['expect_5feq_20null_20ptr_20tt_20and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_62',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['expect_5fexit_63',['EXPECT_EXIT',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_EXIT',1,'']]],
  ['expect_5ffalse_64',['EXPECT_FALSE',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_FALSE',1,'']]],
  ['expect_5ffloat_5feq_65',['EXPECT_FLOAT_EQ',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_FLOAT_EQ',1,'']]],
  ['expect_5fge_66',['EXPECT_GE',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_GE',1,'']]],
  ['expect_5fgt_67',['EXPECT_GT',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_GT',1,'']]],
  ['expect_5fhresult_5ffailed_68',['EXPECT_HRESULT_FAILED',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_HRESULT_FAILED',1,'']]],
  ['expect_5fhresult_5fsucceeded_69',['EXPECT_HRESULT_SUCCEEDED',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_HRESULT_SUCCEEDED',1,'']]],
  ['expect_5fle_70',['EXPECT_LE',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_LE',1,'']]],
  ['expect_5flt_71',['EXPECT_LT',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_LT',1,'']]],
  ['expect_5fne_72',['EXPECT_NE',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_NE',1,'']]],
  ['expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_73',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['expect_5fnear_74',['EXPECT_NEAR',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_NEAR',1,'']]],
  ['expect_5fno_5fthrow_75',['EXPECT_NO_THROW',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_NO_THROW',1,'']]],
  ['expect_5fpred_76',['EXPECT_PRED*',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_PRED',1,'']]],
  ['expect_5fpred_5fformat_77',['EXPECT_PRED_FORMAT*',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_PRED_FORMAT',1,'']]],
  ['expect_5fstrcaseeq_78',['EXPECT_STRCASEEQ',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_STRCASEEQ',1,'']]],
  ['expect_5fstrcasene_79',['EXPECT_STRCASENE',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_STRCASENE',1,'']]],
  ['expect_5fstreq_80',['EXPECT_STREQ',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_STREQ',1,'']]],
  ['expect_5fstrne_81',['EXPECT_STRNE',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_STRNE',1,'']]],
  ['expect_5fthat_82',['EXPECT_THAT',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_THAT',1,'']]],
  ['expect_5fthrow_83',['EXPECT_THROW',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_THROW',1,'']]],
  ['expect_5ftrue_84',['EXPECT_TRUE',['../md_extern_2googletest_2docs_2reference_2assertions.html#EXPECT_TRUE',1,'']]],
  ['expectation_85',['Expectation',['../md_extern_2googletest_2docs_2reference_2mocking.html#Expectation',1,'']]],
  ['expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_86',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['expectation_20order_87',['Expectation Order',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md113',1,'']]],
  ['expectation_20ordering_88',['Expectation Ordering',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md212',1,'']]],
  ['expectation_20retires_89',['Controlling When an Expectation Retires',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md144',1,'']]],
  ['expectations_90',['Expectations',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#ExpectCall',1,'Setting Expectations'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md141',1,'Setting Expectations'],['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md213',1,'Setting Expectations'],['../md_extern_2googletest_2docs_2gmock__for__dummies.html#MultiExpectations',1,'Using Multiple Expectations']]],
  ['expectations_20are_20not_20satisfied_20what_20should_20i_20do_91',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['expectations_20are_20sticky_20unless_20said_20otherwise_92',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['expectations_20awkward_20why_20does_20gmock_20do_20that_93',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['expectations_20override_20older_20ones_20rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_94',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['expectationset_95',['ExpectationSet',['../md_extern_2googletest_2docs_2reference_2mocking.html#ExpectationSet',1,'']]],
  ['expectcalltest_96',['ExpectCallTest',['../classtesting_1_1gmock__function__mocker__test_1_1ExpectCallTest.html',1,'testing::gmock_function_mocker_test']]],
  ['expectfailuretest_97',['ExpectFailureTest',['../classExpectFailureTest.html',1,'']]],
  ['expecting_20ordered_20calls_98',['Expecting Ordered Calls',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#OrderedCalls',1,'']]],
  ['expecting_20partially_20ordered_20calls_99',['Expecting Partially Ordered Calls',['../md_extern_2googletest_2docs_2gmock__cook__book.html#PartialOrder',1,'']]],
  ['explicit_20success_20and_20failure_100',['Explicit Success and Failure',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md13',1,'Explicit Success and Failure'],['../md_extern_2googletest_2docs_2reference_2assertions.html#success-failure',1,'Explicit Success and Failure']]],
  ['exporting_20api_20symbols_3a_101',['Exporting API symbols:',['../md_extern_2googletest_2googletest_2include_2gtest_2internal_2custom_2README.html#autotoc_md393',1,'']]],
  ['expression_20syntax_102',['Regular Expression Syntax',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md31',1,'']]],
  ['extending_20gmock_103',['Extending gMock',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md166',1,'']]],
  ['extending_20googletest_20by_20handling_20test_20events_104',['Extending GoogleTest by Handling Test Events',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md55',1,'']]],
  ['externalgeneratortest_105',['ExternalGeneratorTest',['../classExternalGeneratorTest.html',1,'']]],
  ['externalinstantiationtest_106',['ExternalInstantiationTest',['../classExternalInstantiationTest.html',1,'']]],
  ['extra_20info_20as_20actions_107',['Using Functions with Extra Info as Actions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md151',1,'']]]
];
