var searchData=
[
  ['random_0',['Random',['../classtesting_1_1internal_1_1Random.html',1,'testing::internal']]],
  ['random_5fnumber_5fgenerator_2ecpp_1',['random_number_generator.cpp',['../random__number__generator_8cpp.html',1,'']]],
  ['random_5fnumber_5fgenerator_2ehpp_2',['random_number_generator.hpp',['../random__number__generator_8hpp.html',1,'']]],
  ['random_5fseed_20unittest_3a_3arandom_5fseed_3',['random_seed {#UnitTest::random_seed}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md319',1,'']]],
  ['randomnumbergenerator_4',['RandomNumberGenerator',['../classRandomNumberGenerator.html',1,'']]],
  ['rangegenerator_5',['RangeGenerator',['../classtesting_1_1internal_1_1RangeGenerator.html',1,'testing::internal']]],
  ['rawbytesprinter_6',['RawBytesPrinter',['../structtesting_1_1internal_1_1RawBytesPrinter.html',1,'testing::internal']]],
  ['readme_7',['README',['../md_README.html',1,'']]],
  ['real_20object_8',['Delegating Calls to a Real Object',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md126',1,'']]],
  ['real_20object_20is_20fine_20what_20can_20be_20wrong_9',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_10',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_11',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['recipes_20on_20using_20gmock_12',['Misc Recipes on Using gMock',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md158',1,'']]],
  ['recordproperty_20test_3a_3arecordproperty_13',['RecordProperty {#Test::RecordProperty}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md285',1,'']]],
  ['redundant_14',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['reference_15',['Reference',['../md_extern_2googletest_2docs_2reference_2actions.html',1,'Actions Reference'],['../md_extern_2googletest_2docs_2reference_2assertions.html',1,'Assertions Reference'],['../md_extern_2googletest_2docs_2reference_2matchers.html',1,'Matchers Reference'],['../md_extern_2googletest_2docs_2reference_2mocking.html',1,'Mocking Reference'],['../md_extern_2googletest_2docs_2reference_2testing.html',1,'Testing Reference']]],
  ['references_20from_20mock_20methods_16',['Returning References from Mock Methods',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md146',1,'']]],
  ['references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_17',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['register_5ftyped_5ftest_5fsuite_5fp_18',['REGISTER_TYPED_TEST_SUITE_P',['../md_extern_2googletest_2docs_2reference_2testing.html#REGISTER_TYPED_TEST_SUITE_P',1,'']]],
  ['registering_20tests_20programmatically_19',['Registering tests programmatically',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md53',1,'']]],
  ['registertest_20',['RegisterTest',['../md_extern_2googletest_2docs_2reference_2testing.html#RegisterTest',1,'']]],
  ['regular_20expression_20syntax_21',['Regular Expression Syntax',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md31',1,'']]],
  ['related_20macros_3a_22',['Flag related macros:',['../md_extern_2googletest_2googlemock_2include_2gmock_2internal_2custom_2README.html#autotoc_md382',1,'']]],
  ['related_20open_20source_20projects_23',['Related Open Source Projects',['../md_extern_2googletest_2README.html#autotoc_md418',1,'']]],
  ['relationtosourcecopy_24',['RelationToSourceCopy',['../structtesting_1_1internal_1_1RelationToSourceCopy.html',1,'testing::internal']]],
  ['relationtosourcereference_25',['RelationToSourceReference',['../structtesting_1_1internal_1_1RelationToSourceReference.html',1,'testing::internal']]],
  ['release_201_2015_200_26',['Release 1.15.0',['../md_extern_2googletest_2README.html#autotoc_md410',1,'']]],
  ['release_20testeventlisteners_3a_3arelease_27',['Release {#TestEventListeners::Release}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md353',1,'']]],
  ['removeconstfromkey_28',['RemoveConstFromKey',['../structtesting_1_1internal_1_1RemoveConstFromKey.html',1,'testing::internal']]],
  ['removeconstfromkey_3c_20std_3a_3apair_3c_20const_20k_2c_20v_20_3e_20_3e_29',['RemoveConstFromKey&lt; std::pair&lt; const K, V &gt; &gt;',['../structtesting_1_1internal_1_1RemoveConstFromKey_3_01std_1_1pair_3_01const_01K_00_01V_01_4_01_4.html',1,'testing::internal']]],
  ['removelocations_30',['RemoveLocations',['../namespacegmock__output__test.html#a59c40167b074a2ef04aecc79a0273f13',1,'gmock_output_test']]],
  ['removememoryaddresses_31',['RemoveMemoryAddresses',['../namespacegmock__output__test.html#ac16c3c4b4875becf250dd73beb381a82',1,'gmock_output_test']]],
  ['removereportheaderandfooter_32',['RemoveReportHeaderAndFooter',['../namespacegmock__output__test.html#acb06643e5e0d0eb85a3bc067e09e56f9',1,'gmock_output_test']]],
  ['removetestnamesofleakedmocks_33',['RemoveTestNamesOfLeakedMocks',['../namespacegmock__output__test.html#ad0a9e9474fb8cb1729c20bc51222c46e',1,'gmock_output_test']]],
  ['repeating_20the_20tests_34',['Repeating the Tests',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md66',1,'']]],
  ['report_35',['Report',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md75',1,'Generating a JSON Report'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md74',1,'Generating an XML Report']]],
  ['reportable_5fdisabled_5ftest_5fcount_20testsuite_3a_3areportable_5fdisabled_5ftest_5fcount_36',['reportable_disabled_test_count {#TestSuite::reportable_disabled_test_count}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md294',1,'']]],
  ['reportable_5fdisabled_5ftest_5fcount_20unittest_3a_3areportable_5fdisabled_5ftest_5fcount_37',['reportable_disabled_test_count {#UnitTest::reportable_disabled_test_count}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md327',1,'']]],
  ['reportable_5ftest_5fcount_20testsuite_3a_3areportable_5ftest_5fcount_38',['reportable_test_count {#TestSuite::reportable_test_count}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md296',1,'']]],
  ['reportable_5ftest_5fcount_20unittest_3a_3areportable_5ftest_5fcount_39',['reportable_test_count {#UnitTest::reportable_test_count}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md329',1,'']]],
  ['reported_40',['Controlling How Failures Are Reported',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md76',1,'']]],
  ['require_20the_20entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20tt_20deathtest_20tt_20when_20it_20uses_20tt_20assert_5fdeath_20tt_41',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['requirements_20for_20contributors_42',['Requirements for Contributors',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md7',1,'']]],
  ['requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_43',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['resetting_20a_20mock_44',['Verifying and Resetting a Mock',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md114',1,'']]],
  ['resources_20between_20tests_20in_20the_20same_20test_20suite_45',['Sharing Resources Between Tests in the Same Test Suite',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['restricting_20the_20type_20of_20an_20argument_20or_20parameter_20in_20an_20action_46',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['result_47',['Ignoring an Action&apos;s Result',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md154',1,'']]],
  ['result_20of_20a_20function_20functor_20or_20callback_48',['Matching the Result of a Function, Functor, or Callback',['../md_extern_2googletest_2docs_2reference_2matchers.html#autotoc_md259',1,'']]],
  ['result_20testinfo_3a_3aresult_49',['result {#TestInfo::result}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md314',1,'']]],
  ['retires_50',['Controlling When an Expectation Retires',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md144',1,'']]],
  ['retiresonsaturation_51',['RetiresOnSaturation {#EXPECT_CALL.RetiresOnSaturation}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md271',1,'']]],
  ['retiresonsaturation_20expect_5fcall_20retiresonsaturation_52',['RetiresOnSaturation {#EXPECT_CALL.RetiresOnSaturation}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md271',1,'']]],
  ['return_20a_20value_20what_20s_20going_20on_53',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['return_20type_54',['Setting the Default Value for a Return Type',['../md_extern_2googletest_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['return_20type_20specified_20what_20does_20it_20mean_55',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['return_20value_20when_20i_20call_20run_5fall_5ftests_20why_56',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['returnaction_57',['ReturnAction',['../classtesting_1_1internal_1_1ReturnAction.html',1,'testing::internal']]],
  ['returnaction_3c_20bymovewrapper_3c_20t_20_3e_20_3e_58',['ReturnAction&lt; ByMoveWrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1ReturnAction_3_01ByMoveWrapper_3_01T_01_4_01_4.html',1,'testing::internal']]],
  ['returnargaction_59',['ReturnArgAction',['../structtesting_1_1internal_1_1ReturnArgAction.html',1,'testing::internal']]],
  ['returning_20a_20value_60',['Returning a Value',['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md246',1,'']]],
  ['returning_20live_20values_20from_20mock_20methods_61',['Returning Live Values from Mock Methods',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['returning_20references_20from_20mock_20methods_62',['Returning References from Mock Methods',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md146',1,'']]],
  ['returnnewaction_63',['ReturnNewAction',['../structtesting_1_1internal_1_1ReturnNewAction.html',1,'testing::internal']]],
  ['returnnullaction_64',['ReturnNullAction',['../classtesting_1_1internal_1_1ReturnNullAction.html',1,'testing::internal']]],
  ['returnpointeeaction_65',['ReturnPointeeAction',['../structtesting_1_1internal_1_1ReturnPointeeAction.html',1,'testing::internal']]],
  ['returnrefaction_66',['ReturnRefAction',['../classtesting_1_1internal_1_1ReturnRefAction.html',1,'testing::internal']]],
  ['returnrefofcopyaction_67',['ReturnRefOfCopyAction',['../classtesting_1_1internal_1_1ReturnRefOfCopyAction.html',1,'testing::internal']]],
  ['returnroundrobinaction_68',['ReturnRoundRobinAction',['../classtesting_1_1internal_1_1ReturnRoundRobinAction.html',1,'testing::internal']]],
  ['returns_20an_20assertionresult_69',['Using a Function That Returns an AssertionResult',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['returnvoidaction_70',['ReturnVoidAction',['../classtesting_1_1internal_1_1ReturnVoidAction.html',1,'testing::internal']]],
  ['routines_71',['Using Assertions in Sub-routines',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['rsquo_20when_20i_20use_20an_20assertion_20what_20gives_72',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_73',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['run_74',['run',['../classApp.html#a8d27eeb51b813760dc39425d7a9a37e2',1,'App']]],
  ['run_20a_20binary_75',['run a binary',['../md_extern_2googletest_2docs_2quickstart-bazel.html#autotoc_md238',1,'Create and run a binary'],['../md_extern_2googletest_2docs_2quickstart-cmake.html#autotoc_md243',1,'Create and run a binary']]],
  ['run_5fall_5ftests_76',['RUN_ALL_TESTS',['../md_extern_2googletest_2docs_2reference_2testing.html#RUN_ALL_TESTS',1,'']]],
  ['run_5fall_5ftests_20why_77',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['run_5fwith_5fflag_78',['run_with_flag',['../namespacegtest__help__test.html#a3bc360e67ea70e1a210d608bdffbd3de',1,'gtest_help_test']]],
  ['runandverify_79',['RunAndVerify',['../classgoogletest-break-on-failure-unittest_1_1GTestBreakOnFailureUnitTest.html#aa10728830adf68f6c0fd9e8ff9a3e5a2',1,'googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.RunAndVerify()'],['../classgoogletest-filter-unittest_1_1GTestFilterUnitTest.html#a210d536f4dd4dc5d8ea687747ca8d6d5',1,'googletest-filter-unittest.GTestFilterUnitTest.RunAndVerify()'],['../classgoogletest-list-tests-unittest_1_1GTestListTestsUnitTest.html#a181f8f8424ac864380a56f443bd571e7',1,'googletest-list-tests-unittest.GTestListTestsUnitTest.RunAndVerify()'],['../classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest.html#a4438abd96792c91b81e3bae28fc27087',1,'googletest-throw-on-failure-test.ThrowOnFailureTest.RunAndVerify()']]],
  ['runandverifyallowingdisabled_80',['RunAndVerifyAllowingDisabled',['../classgoogletest-filter-unittest_1_1GTestFilterUnitTest.html#a8ec218a765232f76b13c81f17c8ee11f',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['runandverifywithsharding_81',['RunAndVerifyWithSharding',['../classgoogletest-filter-unittest_1_1GTestFilterUnitTest.html#a8c4225edcc9ca56e44976fa0d7d84d0b',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['running_20a_20subset_20of_20the_20tests_82',['Running a Subset of the Tests',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['running_20in_20a_20test_83',['How can my code detect if it is running in a test?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md107',1,'']]],
  ['running_20test_20programs_3a_20advanced_20options_84',['Running Test Programs: Advanced Options',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['running_20tests_20in_20emacs_85',['Running Tests in Emacs',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md165',1,'']]],
  ['runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_86',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['runtimes_87',['Visual Studio Dynamic vs Static Runtimes',['../md_extern_2googletest_2googletest_2README.html#autotoc_md400',1,'']]]
];
