var searchData=
[
  ['c_0',['Implementacja algorytmu sortowania przez scalanie w C++',['../md_README.html#autotoc_md420',1,'']]],
  ['c_20runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_1',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['c_20standard_20version_2',['C++ Standard Version',['../md_extern_2googletest_2googletest_2README.html#autotoc_md401',1,'']]],
  ['c_20test_20framework_3',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_extern_2googletest_2README.html#autotoc_md413',1,'']]],
  ['c4301_20or_20c4373_20when_20i_20define_20a_20mock_20method_20with_20a_20const_20parameter_20why_4',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['c4373_20when_20i_20define_20a_20mock_20method_20with_20a_20const_20parameter_20why_5',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['call_20a_20method_20on_20my_20mock_20object_20the_20method_20for_20the_20real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_6',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['call_20encountered_20default_20action_20taken_20should_20i_20panic_7',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md199',1,'']]],
  ['call_20run_5fall_5ftests_20why_8',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['call_20to_20footest_3a_3afootest_20tt_20why_9',['I have a fixture class &lt;tt&gt;FooTest&lt;/tt&gt;, but &lt;tt&gt;TEST_F(FooTest, Bar)&lt;/tt&gt; gives me error &lt;tt&gt;&quot;no matching function for call to `FooTest::FooTest()&apos;&quot;&lt;/tt&gt;. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md100',1,'']]],
  ['call_20when_20i_20use_20tt_20assert_5fpred_20tt_20how_20do_20i_20fix_20it_10',['The compiler complains &quot;no matching function to call&quot; when I use &lt;tt&gt;ASSERT_PRED*&lt;/tt&gt;. How do I fix it?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md92',1,'']]],
  ['callabletag_11',['CallableTag',['../structtesting_1_1OnceAction_3_01Result_07Args_8_8_8_08_4_1_1StdFunctionAdaptor_1_1CallableTag.html',1,'testing::OnceAction&lt; Result(Args...)&gt;::StdFunctionAdaptor']]],
  ['callback_12',['Matching the Result of a Function, Functor, or Callback',['../md_extern_2googletest_2docs_2reference_2matchers.html#autotoc_md259',1,'']]],
  ['callback_20without_20arguments_13',['Invoking a Function/Method/Functor/Lambda/Callback Without Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md152',1,'']]],
  ['called_14',['Cardinalities: How Many Times Will It Be Called?',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md216',1,'']]],
  ['called_15',['How can I assert that a function is NEVER called?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_16',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['called_20why_17',['My SetUp() function is not called. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md95',1,'']]],
  ['calling_20conventions_20for_20mock_20functions_18',['Specifying Calling Conventions for Mock Functions',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md112',1,'']]],
  ['calling_20my_20entire_20test_20suite_20tt_20deathtest_20tt_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_19',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['calls_20',['Calls',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md143',1,'Disallowing Unexpected Calls'],['../md_extern_2googletest_2docs_2gmock__for__dummies.html#OrderedCalls',1,'Expecting Ordered Calls'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#PartialOrder',1,'Expecting Partially Ordered Calls'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md164',1,'Gaining Super Vision into Mock Calls'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md142',1,'Ignoring Uninteresting Calls'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'Understanding Uninteresting vs Unexpected Calls'],['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md218',1,'Uninteresting Calls']]],
  ['calls_20a_20static_20global_20function_20can_20i_20mock_20it_21',['My code calls a static/global function. Can I mock it?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['calls_20to_20a_20fake_22',['Delegating Calls to a Fake',['../md_extern_2googletest_2docs_2gmock__cook__book.html#DelegatingToFake',1,'']]],
  ['calls_20to_20a_20parent_20class_23',['Delegating Calls to a Parent Class',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md127',1,'']]],
  ['calls_20to_20a_20real_20object_24',['Delegating Calls to a Real Object',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md126',1,'']]],
  ['callsmockmethodindestructor_25',['CallsMockMethodInDestructor',['../classtesting_1_1gmock__nice__strict__test_1_1CallsMockMethodInDestructor.html',1,'testing::gmock_nice_strict_test']]],
  ['can_20be_20defined_3a_26',['The following macros can be defined:',['../md_extern_2googletest_2googletest_2include_2gtest_2internal_2custom_2README.html#autotoc_md388',1,'']]],
  ['can_20be_20wrong_27',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['can_20i_20assert_20that_20a_20function_20is_20never_20called_28',['How can I assert that a function is NEVER called?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['can_20i_20delete_20the_20mock_20function_20s_20argument_20in_20an_20action_29',['How can I delete the mock function&apos;s argument in an action?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['can_20i_20derive_20a_20test_20fixture_20from_20another_30',['Can I derive a test fixture from another?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md89',1,'']]],
  ['can_20i_20do_31',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['can_20i_20mock_20a_20variadic_20function_32',['Can I mock a variadic function?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md186',1,'']]],
  ['can_20i_20mock_20it_33',['My code calls a static/global function. Can I mock it?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['can_20i_20perform_20an_20arbitrary_20action_20on_20a_20mock_20function_20s_20argument_34',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_35',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['can_20my_20code_20detect_20if_20it_20is_20running_20in_20a_20test_36',['How can my code detect if it is running in a test?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md107',1,'']]],
  ['can_20t_20figure_20out_20why_20gmock_20thinks_20my_20expectations_20are_20not_20satisfied_20what_20should_20i_20do_37',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['can_20t_20find_20googletest_38',['Help! pkg-config can&apos;t find GoogleTest!',['../md_extern_2googletest_2docs_2pkgconfig.html#autotoc_md223',1,'']]],
  ['can_20the_20statement_20argument_20in_20assert_5fdeath_20be_39',['What can the statement argument in ASSERT_DEATH() be?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md99',1,'']]],
  ['cannot_20return_20a_20value_20what_20s_20going_20on_40',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['cardinalities_41',['Cardinalities',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#CardinalityList',1,'Cardinalities'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md176',1,'Writing New Cardinalities']]],
  ['cardinalities_3a_20how_20many_20times_20will_20it_20be_20called_42',['Cardinalities: How Many Times Will It Be Called?',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md216',1,'']]],
  ['cartesianproductgenerator_43',['CartesianProductGenerator',['../classtesting_1_1internal_1_1CartesianProductGenerator.html',1,'testing::internal']]],
  ['cartesianproductholder_44',['CartesianProductHolder',['../classtesting_1_1internal_1_1CartesianProductHolder.html',1,'testing::internal']]],
  ['case_45',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['case_20for_20mock_20turtles_46',['A Case for Mock Turtles',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md207',1,'']]],
  ['castable_47',['Castable',['../classtesting_1_1internal_1_1Castable.html',1,'testing::internal']]],
  ['casting_20matchers_48',['Casting Matchers',['../md_extern_2googletest_2docs_2gmock__cook__book.html#SafeMatcherCast',1,'']]],
  ['catchcxxexceptionstest_49',['CatchCxxExceptionsTest',['../classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html',1,'googletest-catch-exceptions-test']]],
  ['catching_20failures_50',['&quot;Catching&quot; Failures',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md52',1,'']]],
  ['catching_20test_20thrown_20exceptions_51',['Disabling Catching Test-Thrown Exceptions',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md79',1,'']]],
  ['catchsehexceptionstest_52',['CatchSehExceptionsTest',['../classgoogletest-catch-exceptions-test_1_1CatchSehExceptionsTest.html',1,'googletest-catch-exceptions-test']]],
  ['caveats_53',['Caveats',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md35',1,'']]],
  ['change_20seems_20lost_20after_20the_20death_20test_20finishes_20why_54',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['changes_55',['Contributing Changes',['../md_extern_2googletest_2README.html#autotoc_md419',1,'']]],
  ['changing_20a_20mock_20object_20s_20behavior_20based_20on_20the_20state_56',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['cheat_20sheet_57',['gMock Cheat Sheet',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html',1,'']]],
  ['checking_20for_20failures_20in_20the_20current_20test_58',['Checking for Failures in the Current Test',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md41',1,'']]],
  ['checkpoints_59',['Using Checkpoints',['../md_extern_2googletest_2docs_2gmock__cook__book.html#UsingCheckPoints',1,'']]],
  ['child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_60',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['childclasswithoutstreamoperator_61',['ChildClassWithoutStreamOperator',['../classChildClassWithoutStreamOperator.html',1,'']]],
  ['childclasswithstreamoperator_62',['ChildClassWithStreamOperator',['../classChildClassWithStreamOperator.html',1,'']]],
  ['clashes_63',['Avoiding Macro Name Clashes',['../md_extern_2googletest_2googletest_2README.html#autotoc_md405',1,'']]],
  ['class_64',['Class',['../md_extern_2googletest_2docs_2gmock__cook__book.html#CustomMatcherClass',1,'Defining a Custom Matcher Class'],['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md111',1,'Defining a Mock Class'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md127',1,'Delegating Calls to a Parent Class'],['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#MockClass',1,'Mocking a Normal Class'],['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md208',1,'Writing the Mock Class']]],
  ['class_20and_20microsoft_20visual_20c_20runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_65',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['class_20body_20what_20s_20wrong_66',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_67',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_extern_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['class_20template_68',['Mocking a Class Template',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#MockTemplate',1,'']]],
  ['class_20templates_69',['Mocking Class Templates',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md122',1,'']]],
  ['class_20tt_20footest_20tt_20but_20tt_20test_5ff_20footest_20bar_20tt_20gives_20me_20error_20tt_20no_20matching_20function_20for_20call_20to_20footest_3a_3afootest_20tt_20why_70',['I have a fixture class &lt;tt&gt;FooTest&lt;/tt&gt;, but &lt;tt&gt;TEST_F(FooTest, Bar)&lt;/tt&gt; gives me error &lt;tt&gt;&quot;no matching function for call to `FooTest::FooTest()&apos;&quot;&lt;/tt&gt;. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md100',1,'']]],
  ['classes_71',['Classes',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md125',1,'Alternative to Mocking Concrete Classes'],['../md_extern_2googletest_2docs_2reference_2mocking.html#classes',1,'Classes'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md118',1,'Creating Mock Classes'],['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md115',1,'Mock Classes']]],
  ['classes_20and_20types_72',['Classes and types',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md276',1,'']]],
  ['clear_5farray_73',['CLEAR_ARRAY',['../app_8hpp.html#a5be5e47a3042bc91460d05e47f32120dac8284d89d3bd9f8f0a801abee92e34de',1,'app.hpp']]],
  ['cmake_74',['CMake',['../md_extern_2googletest_2googletest_2README.html#autotoc_md397',1,'Build with CMake'],['../md_extern_2googletest_2docs_2pkgconfig.html#autotoc_md222',1,'CMake'],['../md_extern_2googletest_2docs_2quickstart-cmake.html',1,'Quickstart: Building with CMake']]],
  ['cmake_20project_75',['CMake Project',['../md_extern_2googletest_2googletest_2README.html#autotoc_md399',1,'Incorporating Into An Existing CMake Project'],['../md_extern_2googletest_2googletest_2README.html#autotoc_md398',1,'Standalone CMake Project']]],
  ['code_76',['Code',['../md_extern_2googletest_2docs_2gmock__cook__book.html#SimplerInterfaces',1,'Simplifying the Interface without Breaking Existing Code'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md51',1,'Testing Private Code']]],
  ['code_77',['How to become a contributor and submit your own code',['../md_extern_2googletest_2CONTRIBUTING.html',1,'']]],
  ['code_20calls_20a_20static_20global_20function_20can_20i_20mock_20it_78',['My code calls a static/global function. Can I mock it?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['code_20detect_20if_20it_20is_20running_20in_20a_20test_79',['How can my code detect if it is running in a test?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md107',1,'']]],
  ['codelocation_80',['CodeLocation',['../structtesting_1_1internal_1_1CodeLocation.html',1,'testing::internal']]],
  ['codelocationfortestf_81',['CodeLocationForTESTF',['../classtesting_1_1CodeLocationForTESTF.html',1,'testing']]],
  ['codelocationfortestp_82',['CodeLocationForTESTP',['../classtesting_1_1CodeLocationForTESTP.html',1,'testing']]],
  ['codelocationfortypedtest_83',['CodeLocationForTYPEDTEST',['../classtesting_1_1CodeLocationForTYPEDTEST.html',1,'testing']]],
  ['codelocationfortypedtestp_84',['CodeLocationForTYPEDTESTP',['../classtesting_1_1CodeLocationForTYPEDTESTP.html',1,'testing']]],
  ['colored_20terminal_20output_85',['Colored Terminal Output',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md70',1,'']]],
  ['combining_20actions_86',['Combining Actions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['combining_20matchers_87',['Combining Matchers',['../md_extern_2googletest_2docs_2gmock__cook__book.html#CombiningMatchers',1,'']]],
  ['coming_20soon_88',['Coming Soon',['../md_extern_2googletest_2README.html#autotoc_md412',1,'']]],
  ['commas_89',['Dealing with unprotected commas',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md119',1,'']]],
  ['commenttest_90',['CommentTest',['../classCommentTest.html',1,'']]],
  ['common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_91',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['commontest_92',['CommonTest',['../classCommonTest.html',1,'']]],
  ['communities_93',['The Google Test and Google Mock Communities',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md4',1,'']]],
  ['community_20created_20documentation_94',['Community-Created Documentation',['../md_extern_2googletest_2docs_2community__created__documentation.html',1,'']]],
  ['comparison_95',['Comparison',['../md_extern_2googletest_2docs_2reference_2assertions.html#binary-comparison',1,'Binary Comparison'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md19',1,'Floating-Point Comparison'],['../md_extern_2googletest_2docs_2reference_2assertions.html#floating-point',1,'Floating-Point Comparison'],['../md_extern_2googletest_2docs_2reference_2matchers.html#autotoc_md255',1,'Generic Comparison'],['../md_extern_2googletest_2docs_2reference_2assertions.html#c-strings',1,'String Comparison']]],
  ['compilation_20faster_96',['Making the Compilation Faster',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md160',1,'']]],
  ['compilation_20setting_97',['Using pkg-config in a cross-compilation setting',['../md_extern_2googletest_2docs_2pkgconfig.html#autotoc_md224',1,'']]],
  ['compiler_20complains_20about_20ignoring_20return_20value_20when_20i_20call_20run_5fall_5ftests_20why_98',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['compiler_20complains_20about_20lsquo_20no_20match_20for_20operator_20rsquo_20when_20i_20use_20an_20assertion_20what_20gives_99',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['compiler_20complains_20about_20undefined_20references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_100',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['compiler_20complains_20no_20matching_20function_20to_20call_20when_20i_20use_20tt_20assert_5fpred_20tt_20how_20do_20i_20fix_20it_101',['The compiler complains &quot;no matching function to call&quot; when I use &lt;tt&gt;ASSERT_PRED*&lt;/tt&gt;. How do I fix it?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md92',1,'']]],
  ['compiler_20complains_20that_20a_20constructor_20or_20destructor_20cannot_20return_20a_20value_20what_20s_20going_20on_102',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['compiler_20complains_20void_20value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_103',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md90',1,'']]],
  ['compiler_20errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_104',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md87',1,'']]],
  ['compiling_20it_20what_20can_20i_20do_105',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['complain_20about_20previous_20threads_20that_20were_20already_20joined_106',['Why does ASSERT_DEATH complain about previous threads that were already joined?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md101',1,'']]],
  ['complains_20about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_107',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['complains_20about_20ignoring_20return_20value_20when_20i_20call_20run_5fall_5ftests_20why_108',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['complains_20about_20lsquo_20no_20match_20for_20operator_20rsquo_20when_20i_20use_20an_20assertion_20what_20gives_109',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['complains_20about_20undefined_20references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_110',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['complains_20no_20matching_20function_20to_20call_20when_20i_20use_20tt_20assert_5fpred_20tt_20how_20do_20i_20fix_20it_111',['The compiler complains &quot;no matching function to call&quot; when I use &lt;tt&gt;ASSERT_PRED*&lt;/tt&gt;. How do I fix it?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md92',1,'']]],
  ['complains_20that_20a_20constructor_20or_20destructor_20cannot_20return_20a_20value_20what_20s_20going_20on_112',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['complains_20void_20value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_113',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md90',1,'']]],
  ['complex_20arguments_114',['Verifying Complex Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#SaveArgVerify',1,'']]],
  ['complex_20stuff_20it_20s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_115',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['composite_20actions_116',['Composite Actions',['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md250',1,'']]],
  ['composite_20matchers_117',['Composite Matchers',['../md_extern_2googletest_2docs_2reference_2matchers.html#autotoc_md261',1,'']]],
  ['concepts_118',['Basic Concepts',['../md_extern_2googletest_2docs_2primer.html#autotoc_md229',1,'']]],
  ['concrete_20classes_119',['Alternative to Mocking Concrete Classes',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md125',1,'']]],
  ['conditions_120',['Boolean Conditions',['../md_extern_2googletest_2docs_2reference_2assertions.html#boolean',1,'']]],
  ['config_20can_20t_20find_20googletest_121',['Help! pkg-config can&apos;t find GoogleTest!',['../md_extern_2googletest_2docs_2pkgconfig.html#autotoc_md223',1,'']]],
  ['config_20in_20a_20cross_20compilation_20setting_122',['Using pkg-config in a cross-compilation setting',['../md_extern_2googletest_2docs_2pkgconfig.html#autotoc_md224',1,'']]],
  ['configuration_20for_20multiple_20tests_123',['Test Fixtures: Using the Same Data Configuration for Multiple Tests',['../md_extern_2googletest_2docs_2primer.html#same-data-multiple-tests',1,'']]],
  ['conflicting_20return_20type_20specified_20what_20does_20it_20mean_124',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['conjunction_125',['conjunction',['../structtesting_1_1internal_1_1conjunction.html',1,'testing::internal']]],
  ['conjunction_3c_20p1_20_3e_126',['conjunction&lt; P1 &gt;',['../structtesting_1_1internal_1_1conjunction_3_01P1_01_4.html',1,'testing::internal']]],
  ['conjunction_3c_20p1_2c_20ps_2e_2e_2e_20_3e_127',['conjunction&lt; P1, Ps... &gt;',['../structtesting_1_1internal_1_1conjunction_3_01P1_00_01Ps_8_8_8_01_4.html',1,'testing::internal']]],
  ['const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_128',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['const_20parameter_20why_129',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['const_5fiterator_130',['const_iterator',['../structConstOnlyContainerWithClassIterator_1_1const__iterator.html',1,'ConstOnlyContainerWithClassIterator::const_iterator'],['../structtesting_1_1gtest__printers__test_1_1const__iterator.html',1,'testing::gtest_printers_test::const_iterator']]],
  ['constandnonconstcastable_131',['ConstAndNonConstCastable',['../classtesting_1_1internal_1_1ConstAndNonConstCastable.html',1,'testing::internal']]],
  ['constcastable_132',['ConstCastable',['../classtesting_1_1internal_1_1ConstCastable.html',1,'testing::internal']]],
  ['constcharptr_133',['ConstCharPtr',['../structtesting_1_1internal_1_1ConstCharPtr.html',1,'testing::internal']]],
  ['constonlycontainerwithclassiterator_134',['ConstOnlyContainerWithClassIterator',['../structConstOnlyContainerWithClassIterator.html',1,'']]],
  ['constonlycontainerwithpointeriterator_135',['ConstOnlyContainerWithPointerIterator',['../structConstOnlyContainerWithPointerIterator.html',1,'']]],
  ['constref_136',['ConstRef',['../structtesting_1_1internal_1_1ConstRef.html',1,'testing::internal']]],
  ['constref_3c_20t_20_26_20_3e_137',['ConstRef&lt; T &amp; &gt;',['../structtesting_1_1internal_1_1ConstRef_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['constructfromt_138',['ConstructFromT',['../classConstructFromT.html',1,'']]],
  ['constructioncounting_139',['ConstructionCounting',['../structConstructionCounting.html',1,'']]],
  ['constructor_20destructor_20of_20the_20test_20fixture_20or_20setup_20teardown_140',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_extern_2googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['constructor_20or_20destructor_20cannot_20return_20a_20value_20what_20s_20going_20on_141',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['contain_20underscore_142',['Why should test suite names and test names not contain underscore?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['container_20matchers_143',['Container Matchers',['../md_extern_2googletest_2docs_2reference_2matchers.html#autotoc_md257',1,'']]],
  ['containerhelper_144',['ContainerHelper',['../structtesting_1_1gmock__matchers__test_1_1ContainerHelper.html',1,'testing::gmock_matchers_test']]],
  ['containerprinter_145',['ContainerPrinter',['../structtesting_1_1internal_1_1ContainerPrinter.html',1,'testing::internal']]],
  ['containers_146',['Matching Containers',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md139',1,'']]],
  ['containertest_147',['ContainerTest',['../classContainerTest.html',1,'']]],
  ['contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_148',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['content_20moved_149',['Content Moved',['../md_extern_2googletest_2googlemock_2docs_2README.html',1,'Content Moved'],['../md_extern_2googletest_2googletest_2docs_2README.html',1,'Content Moved']]],
  ['continuous_20integration_150',['Continuous Integration',['../md_extern_2googletest_2README.html#autotoc_md411',1,'']]],
  ['contributing_20a_20patch_151',['Contributing A Patch',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md3',1,'']]],
  ['contributing_20changes_152',['Contributing Changes',['../md_extern_2googletest_2README.html#autotoc_md419',1,'']]],
  ['contributor_20and_20submit_20your_20own_20code_153',['How to become a contributor and submit your own code',['../md_extern_2googletest_2CONTRIBUTING.html',1,'']]],
  ['contributor_20license_20agreements_154',['Contributor License Agreements',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md1',1,'']]],
  ['contributors_155',['Requirements for Contributors',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md7',1,'']]],
  ['controlling_20how_20failures_20are_20reported_156',['Controlling How Failures Are Reported',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md76',1,'']]],
  ['controlling_20how_20much_20information_20gmock_20prints_157',['Controlling How Much Information gMock Prints',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md163',1,'']]],
  ['controlling_20test_20output_158',['Controlling Test Output',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md69',1,'']]],
  ['controlling_20when_20an_20expectation_20retires_159',['Controlling When an Expectation Retires',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md144',1,'']]],
  ['conventions_20for_20mock_20functions_160',['Specifying Calling Conventions for Mock Functions',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md112',1,'']]],
  ['conversionhelperbase_161',['ConversionHelperBase',['../classConversionHelperBase.html',1,'']]],
  ['conversionhelperderived_162',['ConversionHelperDerived',['../classConversionHelperDerived.html',1,'']]],
  ['convertibleglobaltype_163',['ConvertibleGlobalType',['../structConvertibleGlobalType.html',1,'']]],
  ['convertibletoassertionresult_164',['ConvertibleToAssertionResult',['../structConvertibleToAssertionResult.html',1,'']]],
  ['convertibletointegerprinter_165',['ConvertibleToIntegerPrinter',['../structtesting_1_1internal_1_1ConvertibleToIntegerPrinter.html',1,'testing::internal']]],
  ['convertibletostringviewprinter_166',['ConvertibleToStringViewPrinter',['../structtesting_1_1internal_1_1ConvertibleToStringViewPrinter.html',1,'testing::internal']]],
  ['cookbook_167',['gMock Cookbook',['../md_extern_2googletest_2docs_2gmock__cook__book.html',1,'']]],
  ['copyable_168',['Matching Arguments that Are Not Copyable',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md136',1,'']]],
  ['counter_169',['Counter',['../classCounter.html',1,'']]],
  ['crashed_20and_20tt_20scopedmocklog_20tt_20spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_170',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['create_20and_20run_20a_20binary_171',['Create and run a binary',['../md_extern_2googletest_2docs_2quickstart-bazel.html#autotoc_md238',1,'Create and run a binary'],['../md_extern_2googletest_2docs_2quickstart-cmake.html#autotoc_md243',1,'Create and run a binary']]],
  ['created_20documentation_172',['Community-Created Documentation',['../md_extern_2googletest_2docs_2community__created__documentation.html',1,'']]],
  ['created_20using_20gmock_173',['Useful Mocks Created Using gMock',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md183',1,'']]],
  ['creating_20mock_20classes_174',['Creating Mock Classes',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md118',1,'']]],
  ['creating_20value_20parameterized_20abstract_20tests_175',['Creating Value-Parameterized Abstract Tests',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md47',1,'']]],
  ['cross_20compilation_20setting_176',['Using pkg-config in a cross-compilation setting',['../md_extern_2googletest_2docs_2pkgconfig.html#autotoc_md224',1,'']]],
  ['current_20test_177',['Checking for Failures in the Current Test',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md41',1,'']]],
  ['current_20test_20s_20name_178',['Getting the Current Test&apos;s Name',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md54',1,'']]],
  ['current_5ftest_5finfo_20unittest_3a_3acurrent_5ftest_5finfo_179',['current_test_info {#UnitTest::current_test_info}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md318',1,'']]],
  ['current_5ftest_5fsuite_20unittest_3a_3acurrent_5ftest_5fsuite_180',['current_test_suite {#UnitTest::current_test_suite}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md317',1,'']]],
  ['currenttestinfotest_181',['CurrentTestInfoTest',['../classtesting_1_1CurrentTestInfoTest.html',1,'testing']]],
  ['custom_20action_20should_20i_20use_20invoke_20or_20implement_20the_20actioninterface_20interface_182',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['custom_20failure_20messages_183',['Adding Custom Failure Messages',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md168',1,'']]],
  ['custom_20matcher_20class_184',['Defining a Custom Matcher Class',['../md_extern_2googletest_2docs_2gmock__cook__book.html#CustomMatcherClass',1,'']]],
  ['customfunctionnamingtest_185',['CustomFunctionNamingTest',['../classCustomFunctionNamingTest.html',1,'']]],
  ['customfunctornamingtest_186',['CustomFunctorNamingTest',['../classCustomFunctorNamingTest.html',1,'']]],
  ['customintegernamingtest_187',['CustomIntegerNamingTest',['../classCustomIntegerNamingTest.html',1,'']]],
  ['customization_20points_188',['Customization Points',['../md_extern_2googletest_2googlemock_2include_2gmock_2internal_2custom_2README.html',1,'Customization Points'],['../md_extern_2googletest_2googletest_2include_2gtest_2internal_2custom_2README.html',1,'Customization Points']]],
  ['customlambdanamingtest_189',['CustomLambdaNamingTest',['../classCustomLambdaNamingTest.html',1,'']]],
  ['customparamnamefunctor_190',['CustomParamNameFunctor',['../structCustomParamNameFunctor.html',1,'']]],
  ['customstruct_191',['CustomStruct',['../structCustomStruct.html',1,'']]],
  ['customstructnamingtest_192',['CustomStructNamingTest',['../classCustomStructNamingTest.html',1,'']]]
];
