var searchData=
[
  ['lambda_20as_20an_20action_0',['Using a Function, Functor, or Lambda as an Action',['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md248',1,'']]],
  ['lambda_20callback_20without_20arguments_1',['Invoking a Function/Method/Functor/Lambda/Callback Without Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md152',1,'']]],
  ['lambdas_20as_20actions_2',['Using Functions/Methods/Functors/Lambdas as Actions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'']]],
  ['leak_20messages_20on_20windows_3',['How do I suppress the memory leak messages on Windows?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md106',1,'']]],
  ['legacy_20gmock_20faq_4',['Legacy gMock FAQ',['../md_extern_2googletest_2docs_2gmock__faq.html',1,'']]],
  ['legacy_20macro_20based_20actions_5',['Legacy macro-based Actions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md177',1,'']]],
  ['legacy_20macro_20based_20parameterized_20actions_6',['Legacy macro-based parameterized Actions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md178',1,'']]],
  ['legacy_20matcher_20implementation_7',['Legacy Matcher Implementation',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md175',1,'']]],
  ['legacy_20workarounds_20for_20move_20only_20types_8',['Legacy workarounds for move-only types',['../md_extern_2googletest_2docs_2gmock__cook__book.html#LegacyMoveOnly',1,'']]],
  ['legacymockb_9',['LegacyMockB',['../classtesting_1_1gmock__function__mocker__test_1_1LegacyMockB.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockfoo_10',['LegacyMockFoo',['../classtesting_1_1gmock__function__mocker__test_1_1LegacyMockFoo.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes0_11',['LegacyMockMethodSizes0',['../structtesting_1_1gmock__function__mocker__test_1_1LegacyMockMethodSizes0.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes1_12',['LegacyMockMethodSizes1',['../structtesting_1_1gmock__function__mocker__test_1_1LegacyMockMethodSizes1.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes2_13',['LegacyMockMethodSizes2',['../structtesting_1_1gmock__function__mocker__test_1_1LegacyMockMethodSizes2.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes3_14',['LegacyMockMethodSizes3',['../structtesting_1_1gmock__function__mocker__test_1_1LegacyMockMethodSizes3.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes4_15',['LegacyMockMethodSizes4',['../structtesting_1_1gmock__function__mocker__test_1_1LegacyMockMethodSizes4.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockoverloadedonargnumber_16',['LegacyMockOverloadedOnArgNumber',['../classtesting_1_1gmock__function__mocker__test_1_1LegacyMockOverloadedOnArgNumber.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockstack_17',['LegacyMockStack',['../classtesting_1_1gmock__function__mocker__test_1_1LegacyMockStack.html',1,'testing::gmock_function_mocker_test']]],
  ['lessbyname_18',['LessByName',['../structtesting_1_1internal_1_1LessByName.html',1,'testing::internal']]],
  ['library_20dll_19',['As a Shared Library (DLL)',['../md_extern_2googletest_2googletest_2README.html#autotoc_md404',1,'']]],
  ['library_20support_20features_20',['Underlying library support features',['../md_extern_2googletest_2googletest_2include_2gtest_2internal_2custom_2README.html#autotoc_md392',1,'']]],
  ['licencja_20a_21',['&lt;a name=&quot;license&quot;&gt; Licencja&lt;/a&gt;',['../md_README.html#autotoc_md421',1,'']]],
  ['license_20agreements_22',['Contributor License Agreements',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md1',1,'']]],
  ['license_20licencja_20a_23',['&lt;a name=&quot;license&quot;&gt; Licencja&lt;/a&gt;',['../md_README.html#autotoc_md421',1,'']]],
  ['like_20calling_20my_20entire_20test_20suite_20tt_20deathtest_20tt_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_24',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['limitations_25',['Known Limitations',['../md_extern_2googletest_2docs_2primer.html#autotoc_md234',1,'']]],
  ['line_20testinfo_3a_3aline_26',['line {#TestInfo::line}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md310',1,'']]],
  ['line_5fnumber_20testpartresult_3a_3aline_5fnumber_27',['line_number {#TestPartResult::line_number}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md358',1,'']]],
  ['listeners_28',['Listeners',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md56',1,'Defining Event Listeners'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md58',1,'Generating Failures in Listeners'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md57',1,'Using Event Listeners']]],
  ['listeners_20unittest_3a_3alisteners_29',['listeners {#UnitTest::listeners}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md338',1,'']]],
  ['listenertest_30',['ListenerTest',['../classtesting_1_1internal_1_1ListenerTest.html',1,'testing::internal']]],
  ['listing_20test_20names_31',['Listing Test Names',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md61',1,'']]],
  ['live_20at_20head_32',['Live at Head',['../md_extern_2googletest_2README.html#autotoc_md408',1,'']]],
  ['live_20values_20from_20mock_20methods_33',['Returning Live Values from Mock Methods',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['log_20messages_20in_20a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_34',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['log_20messages_20what_20do_20i_20do_35',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md97',1,'']]],
  ['log_20messages_20when_20the_20death_20test_20succeeds_36',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['logging_20additional_20information_37',['Logging Additional Information',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md42',1,'']]],
  ['logging_3a_38',['Logging:',['../md_extern_2googletest_2googletest_2include_2gtest_2internal_2custom_2README.html#autotoc_md390',1,'']]],
  ['logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_39',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_extern_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['lookupblocker_40',['LookupBlocker',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1LookupBlocker.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['lost_20after_20the_20death_20test_20finishes_20why_41',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_42',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['lsquo_20no_20match_20for_20operator_20rsquo_20when_20i_20use_20an_20assertion_20what_20gives_43',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md105',1,'']]]
];
