var searchData=
[
  ['a_0',['&lt;a name=&quot;license&quot;&gt; Licencja&lt;/a&gt;',['../md_README.html#autotoc_md421',1,'']]],
  ['a_20bazel_20workspace_1',['Set up a Bazel workspace',['../md_extern_2googletest_2docs_2quickstart-bazel.html#autotoc_md237',1,'']]],
  ['a_20binary_2',['a binary',['../md_extern_2googletest_2docs_2quickstart-bazel.html#autotoc_md238',1,'Create and run a binary'],['../md_extern_2googletest_2docs_2quickstart-cmake.html#autotoc_md243',1,'Create and run a binary']]],
  ['a_20case_20for_20mock_20turtles_3',['A Case for Mock Turtles',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md207',1,'']]],
  ['a_20class_20template_4',['Mocking a Class Template',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#MockTemplate',1,'']]],
  ['a_20const_20parameter_20why_5',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['a_20constructor_20or_20destructor_20cannot_20return_20a_20value_20what_20s_20going_20on_6',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['a_20contributor_20and_20submit_20your_20own_20code_7',['How to become a contributor and submit your own code',['../md_extern_2googletest_2CONTRIBUTING.html',1,'']]],
  ['a_20cross_20compilation_20setting_8',['Using pkg-config in a cross-compilation setting',['../md_extern_2googletest_2docs_2pkgconfig.html#autotoc_md224',1,'']]],
  ['a_20custom_20action_20should_20i_20use_20invoke_20or_20implement_20the_20actioninterface_20interface_9',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['a_20custom_20matcher_20class_10',['Defining a Custom Matcher Class',['../md_extern_2googletest_2docs_2gmock__cook__book.html#CustomMatcherClass',1,'']]],
  ['a_20death_20test_11',['How to Write a Death Test',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md29',1,'']]],
  ['a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_12',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['a_20failed_20test_20where_20gmock_20tells_20me_20twice_20that_20a_20particular_20expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_13',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['a_20fake_14',['Delegating Calls to a Fake',['../md_extern_2googletest_2docs_2gmock__cook__book.html#DelegatingToFake',1,'']]],
  ['a_20fixture_20class_20tt_20footest_20tt_20but_20tt_20test_5ff_20footest_20bar_20tt_20gives_20me_20error_20tt_20no_20matching_20function_20for_20call_20to_20footest_3a_3afootest_20tt_20why_15',['I have a fixture class &lt;tt&gt;FooTest&lt;/tt&gt;, but &lt;tt&gt;TEST_F(FooTest, Bar)&lt;/tt&gt; gives me error &lt;tt&gt;&quot;no matching function for call to `FooTest::FooTest()&apos;&quot;&lt;/tt&gt;. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md100',1,'']]],
  ['a_20function_20functor_20or_20callback_16',['Matching the Result of a Function, Functor, or Callback',['../md_extern_2googletest_2docs_2reference_2matchers.html#autotoc_md259',1,'']]],
  ['a_20function_20functor_20or_20lambda_20as_20an_20action_17',['Using a Function, Functor, or Lambda as an Action',['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md248',1,'']]],
  ['a_20function_20is_20never_20called_18',['How can I assert that a function is NEVER called?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['a_20function_20method_20functor_20lambda_20callback_20without_20arguments_19',['Invoking a Function/Method/Functor/Lambda/Callback Without Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md152',1,'']]],
  ['a_20function_20that_20returns_20an_20assertionresult_20',['Using a Function That Returns an AssertionResult',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['a_20function_20without_20expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_21',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['a_20gmock_20bug_22',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['a_20googler_23',['Are you a Googler?',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md2',1,'']]],
  ['a_20googletest_20bug_24',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md87',1,'']]],
  ['a_20heapcheck_20failure_20when_20using_20a_20mock_20object_20but_20using_20a_20real_20object_20is_20fine_20what_20can_20be_20wrong_25',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['a_20huge_20mock_20class_20and_20microsoft_20visual_20c_20runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_26',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['a_20json_20report_27',['Generating a JSON Report',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md75',1,'']]],
  ['a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_28',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['a_20member_20of_20an_20object_29',['Validating a Member of an Object',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md137',1,'']]],
  ['a_20method_20on_20my_20mock_20object_20the_20method_20for_20the_20real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_30',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['a_20mock_31',['Verifying and Resetting a Mock',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md114',1,'']]],
  ['a_20mock_20class_32',['Defining a Mock Class',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md111',1,'']]],
  ['a_20mock_20function_20s_20argument_33',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['a_20mock_20method_34',['Setting the Default Actions for a Mock Method',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md150',1,'']]],
  ['a_20mock_20method_20with_20a_20const_20parameter_20why_35',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['a_20mock_20object_20but_20using_20a_20real_20object_20is_20fine_20what_20can_20be_20wrong_36',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['a_20mock_20object_20s_20behavior_20based_20on_20the_20state_37',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['a_20name_20license_20licencja_20a_38',['&lt;a name=&quot;license&quot;&gt; Licencja&lt;/a&gt;',['../md_README.html#autotoc_md421',1,'']]],
  ['a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_39',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_extern_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['a_20normal_20class_40',['Mocking a Normal Class',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#MockClass',1,'']]],
  ['a_20parent_20class_41',['Delegating Calls to a Parent Class',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md127',1,'']]],
  ['a_20particular_20expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_42',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['a_20patch_43',['Contributing A Patch',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md3',1,'']]],
  ['a_20pointer_20argument_44',['Validating the Value Pointed to by a Pointer Argument',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['a_20predicate_20formatter_45',['Using a Predicate-Formatter',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md18',1,'']]],
  ['a_20project_46',['Set up a project',['../md_extern_2googletest_2docs_2quickstart-cmake.html#autotoc_md242',1,'']]],
  ['a_20real_20object_47',['Delegating Calls to a Real Object',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md126',1,'']]],
  ['a_20real_20object_20is_20fine_20what_20can_20be_20wrong_48',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['a_20return_20type_49',['Setting the Default Value for a Return Type',['../md_extern_2googletest_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['a_20shared_20library_20dll_50',['As a Shared Library (DLL)',['../md_extern_2googletest_2googletest_2README.html#autotoc_md404',1,'']]],
  ['a_20static_20global_20function_20can_20i_20mock_20it_51',['My code calls a static/global function. Can I mock it?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['a_20subset_20of_20the_20tests_52',['Running a Subset of the Tests',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['a_20test_53',['a test',['../md_extern_2googletest_2docs_2faq.html#autotoc_md107',1,'How can my code detect if it is running in a test?'],['../md_extern_2googletest_2docs_2faq.html#autotoc_md108',1,'How do I temporarily disable a test?']]],
  ['a_20test_20fixture_20from_20another_54',['Can I derive a test fixture from another?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md89',1,'']]],
  ['a_20value_55',['Returning a Value',['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md246',1,'']]],
  ['a_20value_20what_20s_20going_20on_56',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['a_20variadic_20function_57',['Can I mock a variadic function?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md186',1,'']]],
  ['a_20verification_58',['Forcing a Verification',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md161',1,'']]],
  ['a_20warning_20uninteresting_20function_20call_20encountered_20default_20action_20taken_20should_20i_20panic_59',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md199',1,'']]],
  ['a_20warning_20when_20a_20function_20without_20expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_60',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['a_20whole_61',['Matching Multiple Arguments as a Whole',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md132',1,'']]],
  ['a_20whole_20bunch_20of_20log_20messages_20what_20do_20i_20do_62',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md97',1,'']]],
  ['about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_63',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['about_20ignoring_20return_20value_20when_20i_20call_20run_5fall_5ftests_20why_64',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['about_20lsquo_20no_20match_20for_20operator_20rsquo_20when_20i_20use_20an_20assertion_20what_20gives_65',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['about_20previous_20threads_20that_20were_20already_20joined_66',['Why does ASSERT_DEATH complain about previous threads that were already joined?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md101',1,'']]],
  ['about_20undefined_20references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_67',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['abstract_20tests_68',['Creating Value-Parameterized Abstract Tests',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md47',1,'']]],
  ['action_69',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['action_70',['Action',['../classtesting_1_1Action.html',1,'testing::Action&lt; F &gt;'],['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md249',1,'Default Action'],['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md248',1,'Using a Function, Functor, or Lambda as an Action']]],
  ['action_71',['How can I delete the mock function&apos;s argument in an action?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['action_20functions_72',['Ignoring Arguments in Action Functions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md155',1,'']]],
  ['action_20object_20s_20type_73',['Using the ACTION Object&apos;s Type',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md181',1,'']]],
  ['action_20on_20a_20mock_20function_20s_20argument_74',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['action_20s_20arguments_75',['Selecting an Action&apos;s Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['action_20s_20result_76',['Ignoring an Action&apos;s Result',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md154',1,'']]],
  ['action_20should_20i_20use_20invoke_20or_20implement_20the_20actioninterface_20interface_77',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['action_20taken_20should_20i_20panic_78',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md199',1,'']]],
  ['action_20templates_20quickly_79',['Writing New Action Templates Quickly',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md180',1,'']]],
  ['action_3c_20originalfunction_20_3e_80',['Action&lt; OriginalFunction &gt;',['../classtesting_1_1Action.html',1,'testing']]],
  ['action_3c_20r_28args_2e_2e_2e_29_3e_81',['Action&lt; R(Args...)&gt;',['../classtesting_1_1Action_3_01R_07Args_8_8_8_08_4.html',1,'testing']]],
  ['actionimpl_82',['ActionImpl',['../structtesting_1_1internal_1_1ActionImpl.html',1,'testing::internal']]],
  ['actionimpl_3c_20r_28args_2e_2e_2e_29_2c_20impl_20_3e_83',['ActionImpl&lt; R(Args...), Impl &gt;',['../structtesting_1_1internal_1_1ActionImpl_3_01R_07Args_8_8_8_08_00_01Impl_01_4.html',1,'testing::internal']]],
  ['actioninterface_84',['ActionInterface',['../classtesting_1_1ActionInterface.html',1,'testing']]],
  ['actioninterface_20interface_85',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['actions_86',['Actions',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#ActionList',1,'Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md148',1,'Combining Actions'],['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md250',1,'Composite Actions'],['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md251',1,'Defining Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md177',1,'Legacy macro-based Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md178',1,'Legacy macro-based parameterized Actions'],['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#OnCall',1,'Setting Default Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md156',1,'Sharing Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md145',1,'Using Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md151',1,'Using Functions with Extra Info as Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'Using Functions/Methods/Functors/Lambdas as Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#QuickNewActions',1,'Writing New Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#NewMonoActions',1,'Writing New Monomorphic Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#NewPolyActions',1,'Writing New Polymorphic Actions']]],
  ['actions_20based_20on_20the_20arguments_87',['Performing Different Actions Based on the Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md131',1,'']]],
  ['actions_20for_20a_20mock_20method_88',['Setting the Default Actions for a Mock Method',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md150',1,'']]],
  ['actions_20gmock_20sucks_89',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['actions_20reference_90',['Actions Reference',['../md_extern_2googletest_2docs_2reference_2actions.html',1,'']]],
  ['actions_3a_20what_20should_20it_20do_91',['Actions: What Should It Do?',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md217',1,'']]],
  ['ad_5fhoc_5ftest_5fresult_20testsuite_3a_3aad_5fhoc_5ftest_5fresult_92',['ad_hoc_test_result {#TestSuite::ad_hoc_test_result}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md304',1,'']]],
  ['ad_5fhoc_5ftest_5fresult_20unittest_3a_3aad_5fhoc_5ftest_5fresult_93',['ad_hoc_test_result {#UnitTest::ad_hoc_test_result}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md337',1,'']]],
  ['adapters_20for_20matchers_94',['Adapters for Matchers',['../md_extern_2googletest_2docs_2reference_2matchers.html#autotoc_md262',1,'']]],
  ['add_5ffailure_95',['ADD_FAILURE',['../md_extern_2googletest_2docs_2reference_2assertions.html#ADD_FAILURE',1,'']]],
  ['add_5ffailure_5fat_96',['ADD_FAILURE_AT',['../md_extern_2googletest_2docs_2reference_2assertions.html#ADD_FAILURE_AT',1,'']]],
  ['addglobaltestenvironment_97',['AddGlobalTestEnvironment',['../md_extern_2googletest_2docs_2reference_2testing.html#AddGlobalTestEnvironment',1,'']]],
  ['adding_20custom_20failure_20messages_98',['Adding Custom Failure Messages',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md168',1,'']]],
  ['adding_20traces_20to_20assertions_99',['Adding Traces to Assertions',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md37',1,'']]],
  ['additional_20information_100',['Logging Additional Information',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md42',1,'']]],
  ['adjustforparameterizedtests_101',['AdjustForParameterizedTests',['../classgoogletest-filter-unittest_1_1GTestFilterUnitTest.html#ad3255c47638058bf79131ac44fa2cf49',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['advanced_20googletest_20topics_102',['Advanced GoogleTest Topics',['../md_extern_2googletest_2docs_2advanced.html',1,'']]],
  ['advanced_20options_103',['Running Test Programs: Advanced Options',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['after_104',['After {#EXPECT_CALL.After}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md268',1,'']]],
  ['after_20expect_5fcall_20after_105',['After {#EXPECT_CALL.After}',['../md_extern_2googletest_2docs_2reference_2mocking.html#autotoc_md268',1,'']]],
  ['after_20the_20death_20test_20finishes_20why_106',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['agreements_107',['Contributor License Agreements',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md1',1,'']]],
  ['ahashtable_108',['AHashTable',['../structAHashTable.html',1,'']]],
  ['algorytmu_20sortowania_20przez_20scalanie_20w_20c_109',['Implementacja algorytmu sortowania przez scalanie w C++',['../md_README.html#autotoc_md420',1,'']]],
  ['all_20expectations_20are_20sticky_20unless_20said_20otherwise_110',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['allowsgenericstreaming_111',['AllowsGenericStreaming',['../classtesting_1_1gtest__printers__test_1_1AllowsGenericStreaming.html',1,'testing::gtest_printers_test']]],
  ['allowsgenericstreamingandimplicitconversiontemplate_112',['AllowsGenericStreamingAndImplicitConversionTemplate',['../classtesting_1_1gtest__printers__test_1_1AllowsGenericStreamingAndImplicitConversionTemplate.html',1,'testing::gtest_printers_test']]],
  ['allowsgenericstreamingtemplate_113',['AllowsGenericStreamingTemplate',['../classtesting_1_1gtest__printers__test_1_1AllowsGenericStreamingTemplate.html',1,'testing::gtest_printers_test']]],
  ['already_20joined_114',['Why does ASSERT_DEATH complain about previous threads that were already joined?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md101',1,'']]],
  ['alternatecallable_115',['AlternateCallable',['../structtesting_1_1gmock__function__mocker__test_1_1AlternateCallable.html',1,'testing::gmock_function_mocker_test']]],
  ['alternative_20to_20mocking_20concrete_20classes_116',['Alternative to Mocking Concrete Classes',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md125',1,'']]],
  ['an_20action_117',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['an_20action_118',['Using a Function, Functor, or Lambda as an Action',['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md248',1,'']]],
  ['an_20action_119',['How can I delete the mock function&apos;s argument in an action?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['an_20action_20s_20arguments_120',['Selecting an Action&apos;s Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['an_20action_20s_20result_121',['Ignoring an Action&apos;s Result',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md154',1,'']]],
  ['an_20arbitrary_20action_20on_20a_20mock_20function_20s_20argument_122',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['an_20argument_20of_20the_20mock_20function_123',['Invoking an Argument of the Mock Function',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md153',1,'']]],
  ['an_20argument_20or_20parameter_20in_20an_20action_124',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['an_20assertion_20what_20gives_125',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['an_20assertionresult_126',['Using a Function That Returns an AssertionResult',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['an_20exception_127',['Asserting on Subroutines with an exception',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['an_20existing_20boolean_20function_128',['Using an Existing Boolean Function',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md16',1,'']]],
  ['an_20existing_20cmake_20project_129',['Incorporating Into An Existing CMake Project',['../md_extern_2googletest_2googletest_2README.html#autotoc_md399',1,'']]],
  ['an_20expectation_20retires_130',['Controlling When an Expectation Retires',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md144',1,'']]],
  ['an_20interface_20satisfy_20some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_131',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['an_20object_132',['Validating a Member of an Object',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md137',1,'']]],
  ['an_20xml_20report_133',['Generating an XML Report',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md74',1,'']]],
  ['and_20failure_134',['and Failure',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md13',1,'Explicit Success and Failure'],['../md_extern_2googletest_2docs_2reference_2assertions.html#success-failure',1,'Explicit Success and Failure']]],
  ['and_20google_20mock_135',['Developing Google Test and Google Mock',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md8',1,'']]],
  ['and_20google_20mock_20communities_136',['The Google Test and Google Mock Communities',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md4',1,'']]],
  ['and_20google_20mock_20themselves_137',['Testing Google Test and Google Mock Themselves',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md9',1,'']]],
  ['and_20microsoft_20visual_20c_20runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_138',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['and_20non_20death_20tests_20what_20do_20i_20do_139',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['and_20resetting_20a_20mock_140',['Verifying and Resetting a Mock',['../md_extern_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md114',1,'']]],
  ['and_20run_20a_20binary_141',['and run a binary',['../md_extern_2googletest_2docs_2quickstart-bazel.html#autotoc_md238',1,'Create and run a binary'],['../md_extern_2googletest_2docs_2quickstart-cmake.html#autotoc_md243',1,'Create and run a binary']]],
  ['and_20submit_20your_20own_20code_142',['How to become a contributor and submit your own code',['../md_extern_2googletest_2CONTRIBUTING.html',1,'']]],
  ['and_20tear_20down_143',['Global Set-Up and Tear-Down',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md44',1,'']]],
  ['and_20test_20names_20not_20contain_20underscore_144',['Why should test suite names and test names not contain underscore?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['and_20the_20naggy_145',['The Nice, the Strict, and the Naggy',['../md_extern_2googletest_2docs_2gmock__cook__book.html#NiceStrictNaggy',1,'']]],
  ['and_20threads_146',['Death Tests And Threads',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md33',1,'']]],
  ['and_20threads_147',['Using gMock and Threads',['../md_extern_2googletest_2docs_2gmock__cook__book.html#UsingThreads',1,'']]],
  ['and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_148',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['and_20tt_20assert_5fne_20null_20ptr_20tt_149',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['and_20tt_20scopedmocklog_20tt_20spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_150',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['and_20types_151',['Classes and types',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md276',1,'']]],
  ['announcements_152',['Announcements',['../md_extern_2googletest_2README.html#autotoc_md407',1,'']]],
  ['another_153',['Can I derive a test fixture from another?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md89',1,'']]],
  ['api_20symbols_3a_154',['Exporting API symbols:',['../md_extern_2googletest_2googletest_2include_2gtest_2internal_2custom_2README.html#autotoc_md393',1,'']]],
  ['app_155',['App',['../classApp.html',1,'']]],
  ['app_2ecpp_156',['app.cpp',['../app_8cpp.html',1,'']]],
  ['app_2ehpp_157',['app.hpp',['../app_8hpp.html',1,'']]],
  ['append_20testeventlisteners_3a_3aappend_158',['Append {#TestEventListeners::Append}',['../md_extern_2googletest_2docs_2reference_2testing.html#autotoc_md352',1,'']]],
  ['arbitrary_20action_20on_20a_20mock_20function_20s_20argument_159',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['are_20not_20copyable_160',['Matching Arguments that Are Not Copyable',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md136',1,'']]],
  ['are_20not_20satisfied_20what_20should_20i_20do_161',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['are_20reported_162',['Controlling How Failures Are Reported',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md76',1,'']]],
  ['are_20sticky_20unless_20said_20otherwise_163',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['are_20you_20a_20googler_164',['Are you a Googler?',['../md_extern_2googletest_2CONTRIBUTING.html#autotoc_md2',1,'']]],
  ['argument_165',['Validating the Value Pointed to by a Pointer Argument',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['argument_166',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['argument_20in_20an_20action_167',['How can I delete the mock function&apos;s argument in an action?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['argument_20in_20assert_5fdeath_20be_168',['What can the statement argument in ASSERT_DEATH() be?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md99',1,'']]],
  ['argument_20matchers_169',['Multi-argument Matchers',['../md_extern_2googletest_2docs_2reference_2matchers.html#MultiArgMatchers',1,'']]],
  ['argument_20of_20the_20mock_20function_170',['Invoking an Argument of the Mock Function',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md153',1,'']]],
  ['argument_20or_20parameter_20in_20an_20action_171',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['argument_20types_172',['Argument Types',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md171',1,'']]],
  ['argument_20values_20exactly_173',['Matching Argument Values Exactly',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md129',1,'']]],
  ['arguments_174',['Arguments',['../md_extern_2googletest_2docs_2gmock__cook__book.html#ParameterlessExpectations',1,'Ignoring Uninteresting Arguments'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md152',1,'Invoking a Function/Method/Functor/Lambda/Callback Without Arguments'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md131',1,'Performing Different Actions Based on the Arguments'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#SelectingArgs',1,'Selecting an Action&apos;s Arguments'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#SaveArgVerify',1,'Verifying Complex Arguments']]],
  ['arguments_20as_20a_20whole_175',['Matching Multiple Arguments as a Whole',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md132',1,'']]],
  ['arguments_20do_20we_20expect_176',['Matchers: What Arguments Do We Expect?',['../md_extern_2googletest_2docs_2gmock__for__dummies.html#autotoc_md215',1,'']]],
  ['arguments_20in_20action_20functions_177',['Ignoring Arguments in Action Functions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md155',1,'']]],
  ['arguments_20that_20are_20not_20copyable_178',['Matching Arguments that Are Not Copyable',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md136',1,'']]],
  ['array_5futils_2ecpp_179',['array_utils.cpp',['../array__utils_8cpp.html',1,'']]],
  ['array_5futils_2ehpp_180',['array_utils.hpp',['../array__utils_8hpp.html',1,'']]],
  ['as_20a_20shared_20library_20dll_181',['As a Shared Library (DLL)',['../md_extern_2googletest_2googletest_2README.html#autotoc_md404',1,'']]],
  ['as_20a_20whole_182',['Matching Multiple Arguments as a Whole',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md132',1,'']]],
  ['as_20actions_183',['as Actions',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md151',1,'Using Functions with Extra Info as Actions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'Using Functions/Methods/Functors/Lambdas as Actions']]],
  ['as_20an_20action_184',['Using a Function, Functor, or Lambda as an Action',['../md_extern_2googletest_2docs_2reference_2actions.html#autotoc_md248',1,'']]],
  ['as_20it_20ought_20to_20be_20what_20does_20this_20mean_185',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md90',1,'']]],
  ['as_20matchers_186',['Using Predicates as Matchers',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md135',1,'']]],
  ['as_20predicates_187',['as Predicates',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md133',1,'Using Matchers as Predicates'],['../md_extern_2googletest_2docs_2reference_2matchers.html#MatchersAsPredicatesCheat',1,'Using Matchers as Predicates']]],
  ['assert_20that_20a_20function_20is_20never_20called_188',['How can I assert that a function is NEVER called?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['assert_5fdeath_20be_189',['What can the statement argument in ASSERT_DEATH() be?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md99',1,'']]],
  ['assert_5fdeath_20complain_20about_20previous_20threads_20that_20were_20already_20joined_190',['Why does ASSERT_DEATH complain about previous threads that were already joined?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md101',1,'']]],
  ['assert_5fdeath_20tt_191',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_192',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['assert_5fne_20null_20ptr_20tt_193',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['assert_5fpred_20tt_20how_20do_20i_20fix_20it_194',['The compiler complains &quot;no matching function to call&quot; when I use &lt;tt&gt;ASSERT_PRED*&lt;/tt&gt;. How do I fix it?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md92',1,'']]],
  ['assertequivalentnodes_195',['AssertEquivalentNodes',['../classgtest__xml__test__utils_1_1GTestXMLTestCase.html#aa18d40539741ab7357616c9557781e82',1,'gtest_xml_test_utils::GTestXMLTestCase']]],
  ['assertfailfastbehavior_196',['assertFailFastBehavior',['../classgoogletest-failfast-unittest_1_1GTestFailFastUnitTest.html#a03650c7b544b443cb7dd28544173bb98',1,'googletest-failfast-unittest::GTestFailFastUnitTest']]],
  ['assertfailfastxmlandtxtoutput_197',['assertFailFastXmlAndTxtOutput',['../classgoogletest-failfast-unittest_1_1GTestFailFastUnitTest.html#a47569a2ba1633f460d9892b487770f25',1,'googletest-failfast-unittest::GTestFailFastUnitTest']]],
  ['asserthelper_198',['AssertHelper',['../classtesting_1_1internal_1_1AssertHelper.html',1,'testing::internal']]],
  ['asserting_20on_20subroutines_199',['Asserting on Subroutines',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md40',1,'']]],
  ['asserting_20on_20subroutines_20with_20an_20exception_200',['Asserting on Subroutines with an exception',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['asserting_20using_20gmock_20matchers_201',['Asserting Using gMock Matchers',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md21',1,'']]],
  ['assertion_202',['Generalized Assertion',['../md_extern_2googletest_2docs_2reference_2assertions.html#generalized',1,'']]],
  ['assertion_20failures_20into_20break_20points_203',['Turning Assertion Failures into Break-Points',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md78',1,'']]],
  ['assertion_20placement_204',['Assertion Placement',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md25',1,'']]],
  ['assertion_20what_20gives_205',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_extern_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['assertionexception_206',['AssertionException',['../md_extern_2googletest_2docs_2reference_2testing.html#AssertionException',1,'']]],
  ['assertionfailure_207',['AssertionFailure',['../md_extern_2googletest_2docs_2reference_2testing.html#AssertionFailure',1,'']]],
  ['assertionresult_208',['AssertionResult',['../classmy__namespace_1_1testing_1_1AssertionResult.html',1,'my_namespace::testing::AssertionResult'],['../md_extern_2googletest_2docs_2reference_2testing.html#AssertionResult',1,'AssertionResult'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md17',1,'Using a Function That Returns an AssertionResult']]],
  ['assertions_209',['Assertions',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md37',1,'Adding Traces to Assertions'],['../md_extern_2googletest_2docs_2primer.html#autotoc_md230',1,'Assertions'],['../md_extern_2googletest_2docs_2reference_2assertions.html#death',1,'Death Assertions'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md14',1,'Exception Assertions'],['../md_extern_2googletest_2docs_2reference_2assertions.html#exceptions',1,'Exception Assertions'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md12',1,'More Assertions'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md22',1,'More String Assertions'],['../md_extern_2googletest_2docs_2reference_2assertions.html#predicates',1,'Predicate Assertions'],['../md_extern_2googletest_2docs_2advanced.html#autotoc_md24',1,'Type Assertions'],['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md134',1,'Using Matchers in googletest Assertions'],['../md_extern_2googletest_2docs_2reference_2assertions.html#HRESULT',1,'Windows HRESULT Assertions']]],
  ['assertions_210',['Windows HRESULT assertions',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md23',1,'']]],
  ['assertions_20for_20better_20error_20messages_211',['Predicate Assertions for Better Error Messages',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md15',1,'']]],
  ['assertions_20in_20sub_20routines_212',['Using Assertions in Sub-routines',['../md_extern_2googletest_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['assertions_20reference_213',['Assertions Reference',['../md_extern_2googletest_2docs_2reference_2assertions.html',1,'']]],
  ['assertionsuccess_214',['AssertionSuccess',['../md_extern_2googletest_2docs_2reference_2testing.html#AssertionSuccess',1,'']]],
  ['assertnotfailfastbehavior_215',['assertNotFailFastBehavior',['../classgoogletest-failfast-unittest_1_1GTestFailFastUnitTest.html#a6aa41abc151212229844a63d8c8add97',1,'googletest-failfast-unittest::GTestFailFastUnitTest']]],
  ['assertpartitionisvalid_216',['AssertPartitionIsValid',['../classgoogletest-filter-unittest_1_1GTestFilterUnitTest.html#acee2acd215c275086078059f1ec76c0f',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['assertsetequal_217',['AssertSetEqual',['../classgoogletest-filter-unittest_1_1GTestFilterUnitTest.html#a5cf5a6f569b64b51b6e159debd1964ef',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['assignaction_218',['AssignAction',['../classtesting_1_1internal_1_1AssignAction.html',1,'testing::internal']]],
  ['asynchronous_20behavior_219',['Testing Asynchronous Behavior',['../md_extern_2googletest_2docs_2gmock__cook__book.html#autotoc_md157',1,'']]],
  ['at_20head_220',['Live at Head',['../md_extern_2googletest_2README.html#autotoc_md408',1,'']]],
  ['avoiding_20macro_20name_20clashes_221',['Avoiding Macro Name Clashes',['../md_extern_2googletest_2googletest_2README.html#autotoc_md405',1,'']]],
  ['awkward_20why_20does_20gmock_20do_20that_222',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_extern_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]]
];
